services:
  postgres:
    image: postgres:17.6-alpine3.22
    container_name: newsletter_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personalportfolio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.2.1-alpine
    container_name: newsletter_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

volumes:
  postgres_data:
